version: '2'
services:
    waf:
        image: cybergoof/waf
        container_name: waf
        ports:
        - "8080:80"
        links:
        - dvwa

         
    dvwa:
        image: cybergoof/dvwa
        container_name: dvwa
     