version: '2'
services:
    waf:
        image: cybergoof/waf
        container_name: waf
        volumes:
        - "./logs:/usr/local/nginx/logs"
        ports:
        - "8080:8080"
        links:
        - dvwa

         
    dvwa:
        image: cybergoof/dvwa
        container_name: dvwa
        ports:

     