#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#

# Get function from functions library
. /etc/init.d/functions

# Start the service FOO
start() {
        initlog -c "Starting the Docker Compose Command to start GIAC Application: "
        /path/to/FOO &
        ### Create the lock file ###
        touch /root/docker/6100/logs/error.log
        /usr/local/bin/docker-compose -f /root/docker/6100/docker-compose.yml up -d
        success $"GIAC Application server startup"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping GIAC Application server: "
        /usr/local/bin/docker-compose -f /root/docker/6100/docker-compose.yml down
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0